### ISSUE TITLE
How to send a message in OnApplicationQuit

### ISSUE THREAD

**Issue by jakubgondek** [dwilches/Ardity#1]
I'm trying to use your library, to turn on and off lights in my installation. I also need to turn the lights off when application is turned off. I've put sending off message into OnApplicationQuit, but it doesn't seem to work.

`void OnApplicationQuit()
{
    serialController.SendSerialMessage("@REL#0@");
}`

Is that an expected behaviour?

**Comment by dwilches** [comment]
Hi Jakub,

Indeed, that behaviour is expected because of the execution order of MonoBehaviours' functions:
1. When a game is finishing it invokes the `OnDisable` method of the GameObject that controls the COM port, and then the COM port is closed.
2. Then, Unity invokes the `OnApplicationQuit` method, but by then the COM port is already closed, so your message will never arrive at the other side. 

Check here the order of execution of the functions: https://docs.unity3d.com/Manual/ExecutionOrder.html

Now, there are some solutions:
1. If you can guarantee the `OnDisable` of other of the scripts of that GameObject gets invoked before the `SerialController.OnDisable` then you can send your custom message from there (be sure of adding a delay after sending the message).
2. I will modify the library to include a "tear-down" function, as I think yours will be a pretty common use-case.

Do you want to try with the first option in the meantime? I can add the new functionality later on the weekend.

**Comment by jakubgondek** [comment]
Thanks for fast response. I'll start with OnDisable solution. But how can I add a delay and be sure that the app will wait until it closes? Is adding a coroutine with WaitForSeconds(1); in OnDisable enough?

**Comment by jakubgondek** [comment]
It turns out you cannot place coroutines in OnDisable, and the fact that I'm using Robotlegs Sharp doesn't help either. I'll wait for your "tear-down" implementation, unless you have any other advices for me :)

**Comment by dwilches** [comment]
Hi,
I am at this moment making the last tests for the library to ensure the tear-down works correctly (so far, it does).

It seems weekend arrived earlier than expected :smiley:

**Comment by dwilches** [comment]
Alright, the feature is finished.

Could you give it a try and let me know if it works well for you too?
I put in the README another sample Arduino program, the one I used for testing this feature.
Also, there is a new scene called "DemoSceneUserPoll_ReadWrite_TearDown" where I use the tear-down functionality.
The Unity package was also updated with this change.

**Comment by jakubgondek** [comment]
It works with the device in your supplied test scene. I'll have time to check it in my applilcation tomorrow.

**Comment by dwilches** [comment]
Hello.
Did it work?

**Comment by jakubgondek** [comment]
Sorry for not writing you back. I'm in the middle of a project and it's a little hot in here :) Your teardown method worked for me. Since I'm a fresh C#/Unity programmer i was wondering what's the diffrence between calling:
`
void OnDisable()
{
SendSerialMessage("@REL#0@");
...
`

and

`
void OnDisable()
{
if (userDefinedTearDownFunction != null)
            userDefinedTearDownFunction();
...
`
and `userDefinedTearDownFunction` calling `SendSerialMessage("@REL#0@");` on SerialController? Do delegates hold the execution stack or something?

**Comment by dwilches** [comment]
For this to work:

```
void OnDisable() { SendSerialMessage("@REL#0@");
```

you must modify the `SerialController` file, which is not a good idea with 3rd-party libraries as you will have trouble when upgrading to a new version. Other than that, the lines behave exactly in the same way.

Now, if you meant putting:

```
void OnDisable() { SendSerialMessage("@REL#0@");
```

in a different file, then it won't necessarily work as it depends on which `OnDisable` gets executed first. If `SerialController`'s execute first then by the time the `OnDisable` of your class gets executed, the COM port is already closed.

**Comment by dwilches** [comment]
And about you last question, no, delegates don't hold the execution stack or anything like that, they are plain function pointers.

I guess your question is why it works now, check at the `SerialThread` class, it has an additional change there that was needed so the tear-down worked:

![image](https://cloud.githubusercontent.com/assets/3975401/19277124/df3ba73a-8f95-11e6-8ad3-1be0f0ecb6a7.png)

Now, the `OnDisable` puts something in the "out-queue", and the thread ensures that it doesn't exit while there is something in that queue, so you can think of the queue being the one that holds down the execution of the other `OnDisable`'s.
