### ISSUE TITLE
No able to read messages from com port  

### ISSUE THREAD

**Issue by altafc22** [dwilches/Ardity#27]
first of all thanks to create such useful package, but i'm facing some issue when i'm trying to read message from com port but it  will show '__Connected__' very first time and after that it will not receive any message
can you please tell me some solution to receive message from com port

**Comment by dwilches** [comment]
Hello,

It depends on how you are sending the data to Ardity and how you're reading it (is it an Arduino, is it a specialized chip, are you using the sample Unity scenes, etc.)

Try to troubleshoot each part separately:
* **To know if the problem is in the part sending the data:** You can use the code "Arduino sample code" that you can see here: http://ardity.dwilches.com/ . Put that in your Arduino and check if with that and your **current** Unity code you can see your data.
* **To know if the problem is in the Unity part:** Use one of the included Unity sample scenes to communicate with your **custom** Arduino code.

That way you can know which half is misconfigured.

Also, each device sends data differently, so you need to know which format your data is coming in, which is the line separator, are there lines, etc.

If after this you can't find the issue, provide more details, like what device you are using, what is the expected line separator, etc.

**Comment by altafc22** [comment]
i'm using arduino to send command  like 1 for on and 0 for off
