### ISSUE TITLE
Queue is full problem (interfering arduino with unity)

### ISSUE THREAD

**Issue by pranavkp160** [dwilches/Ardity#48]
I wanted to get the accelerometer data from arduino to unity for creating an AR game.I was using ardity for serial communication.When i run the stimulation along with the accelerometer data iam getting the queue is full message and also the message has been dropped message.How to fix this and how to get full data without droping of datas.Please reply

**Comment by dwilches** [comment]
Hello,
Ensure your Unity program is processing the data quickly. If your Arduino publishes data too quickly, then it will overwhelm Unity if the processing on the Unity side is too slow.

If the problem is Arduino is sending data too fast, you can make it report it more slowly, as anyways Unity won't be able to process all that data on each frame.

Regards.
